#!/usr/bin/env bash
# bash script that  installs the 'ufw' firewall and,
# setup a few rules on 'web-01'

apt-get install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw disable
ufw enable
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
ufw reject proto tcp port 1:21
ufw reject proto tcp port 23
ufw reject proto tcp port 25
ufw reject proto udp port 137:139
ufw reject proto tcp port 445
ufw reject proto udp port 520
ufw reject proto tcp port 12345

ufw reload
