#!/usr/bin/env bash
#transfer files to a server

if [$# -lt 4]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# set params
file="$1"
host="$2"
username="$3"
path_to_ssh_key="$4"

# transfer the data
scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$file" "$username@$host:~/"