#!/usr/bin/env bash
#script to send files to server. 4 params.
#check number of parameters
if [$# -lt 4]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
#params an shit
file="$1"
ip="$2"
username="$3"
path_to_key="$4"

 scp -o "StrictHostKeyChecking no" -i "$path_to_key" "$file" "$username@$ip:~/"