#!/usr/bin/env bash
# Install Nginx web server
sudo apt-get update
sudo apt-get -y install nginx

# Configure redirection
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    # Redirect /redirect_me to another page
    location /redirect_me {
        return 301 https://www.example.com/;
    }

    # Serve the default Nginx welcome page
    root /var/www/html;
    index index.html index.htm;
}" | sudo tee /etc/nginx/sites-available/redirect > /dev/null

# Enable the redirection configuration
sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

# Remove the default Nginx configuration
sudo rm /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo service nginx restart
