#!/usr/bin/env bash

# Install Nginx
apt-get update
apt-get install -y nginx

# Create custom 404 error page
echo "<!DOCTYPE html>
<html>
<head>
  <title>404 Not Found</title>
</head>
<body>
  <h1>404 Not Found</h1>
  <p>Ceci n'est pas une page</p>
</body>
</html>" | sudo tee /var/www/html/404.html >/dev/null

# Update Nginx default server block configuration
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF

# Reload Nginx
systemctl reload nginx
